### ISSUE TITLE
usuń hasło z  kainosinvestmentapp/src/main/resources/application.properties

### ISSUE THREAD

**Issue by BartoszCki** [kwidzinskidawid/kainosinvestmentapp#1]
Udostępniłeś dale logowania do bazy danych w pliku  kainosinvestmentapp/src/main/resources/application.properties. Lepiej usuń to szybko, bo może to zauważyć ktoś mniej uczciwy.

Pozdrawiam
BartoszCki

PS: dodaj nazwę tego pliku do .gitignore i poszukaj w necie jak trwale usunąć plik z repozytorium, bo w poniedziałek ktoś może Ci zrobić kuku ;)

**Comment by kwidzinskidawid** [comment]
Faktycznie, mało to profesjonalne. Dzięki za podpowiedź. Chociaż jest to darmowa baza dzisiaj założona i nie pomyślałem, że ktoś mógłby być złośliwy, to dobrze wyrobić sobie taki nawyk.

Pozdrawiam
